name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Code quality checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: PHPStan
        run: vendor/bin/phpstan analyse --level=8

      - name: PHPCS
        run: vendor/bin/phpcs

      - name: Deptrac
        run: vendor/bin/deptrac analyse --no-progress
